### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by claireinez** [fcscripters/feckless-sniffle#50]
I have no idea what a branch does if it just has your name! You should use a branch that actually describes what the code in it does. Also, try and avoid continually pushing to the same branch - just checkout to a new branch when you are working on new functionality. It makes it much easier to follow the commit history!

**Comment by sohilpandya** [comment]
Thanks @nofootnotes, I think I'm the culprit here. tend to name them sohil all the time. :worried: will use descriptions for the next project or for any further updates in this one :)
